# Generated by Django 3.1.4 on 2020-12-09 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enzyme', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='country',
            new_name='Country',
        ),
    ]
