# Generated by Django 3.1.4 on 2020-12-09 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enzyme', '0002_auto_20201209_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='Country',
            new_name='country',
        ),
    ]
